version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vaultpro_backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=alvezadigital_vaultpro_secret_key_123!
      - FRONTEND_URL=http://localhost:80 # Ganti ini saat deploy ke https://vault.alvezadigital.com
      # Supaya container tidak otomatis mereset SQLite, kita pastikan DATABASE_URL diarahkan ke /app/prisma/dev.db
      - DATABASE_URL=file:./dev.db
    volumes:
      # Mount folder prisma agar file dev.db tidak hilang saat container restart
      - vaultpro_db:/app/prisma

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vaultpro_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  vaultpro_db:
    name: vaultpro_db
